application: mailing-labels
version: 1
runtime: go
api_version: go1
handlers:
- url: /(.*\.(html|css))$
  static_files: static/\1
  upload: static/.*\.(html|css)$
- url: /.*
  script: _go_app
